### ISSUE TITLE
inform the players of new puzzles in classic and expert

### ISSUE THREAD

**Issue by marie-s** [McGill-CSB/PHYLO#105]
you should find a way to inform the players of new puzzles in classic and expert sections like the new puzzles reported in twitter "New DNA puzzles related to Diabetes have been added. All located on Chromosome X. Visit levels 1365 to 1399 #PhyloDNAPuzzles"and expert ones 460 to 480.

**Comment by waldispuhl** [comment]
Thanks for the suggestion. With the expert, the easy way would be to sort the puzzle using their ID (click on the top of the column). This is a bit more tricky with the classic version. Currently, new puzzles have a priority and a much higher probability to be returned when selecting a random one. We're working on new puzzle selection interface though. I hope it'll improve that aspect. Any suggestion is welcome!

**Comment by waldispuhl** [comment]
@marie-s We just posted a text describing our current experiments: http://blogs.cs.mcgill.ca/phylo/2014/05/19/phylo-news-endeavours/. It includes a direct link to the classic puzzles. We will continue to improve this aspect.
