### ISSUE TITLE
miscellaneous/ Andere Erkrankungen

### ISSUE THREAD

**Issue by cateye0434** [McGill-CSB/PHYLO#106]
Unfortunately, I can only pick "Andere Erkrankungen" which is probably a translation of 'Miscellaneous' after reloading the page and starting the selection all over again.
Can anyone do something about it, please?
Thank you.

**Comment by waldispuhl** [comment]
Sorry for the inconvenience. We'll look at it ASAP.

**Comment by cateye0434** [comment]
Thanks a lot.

2014-08-04 8:34 GMT+02:00 waldispuhl notifications@github.com:
