### ISSUE TITLE
Newer browser would stuck in loading.

### ISSUE THREAD

**Issue by miptrel** [McGill-CSB/PHYLO#110]
Hello,

It seems the newer browsers are not supporting PHYLO. The browsers I tried are Firefox 33, Chrome 39. and Safari 7 (under OSX 10.9.5).

The problem is when I opened the webpage (http://phylo.cs.mcgill.ca/ or my localhost), the browser will stuck in loading status ("Setting up! One moment please").

And if I tried open the page with Firefox 28, than it will be loaded successfully.

**Comment by alfredkam** [comment]
Thanks for the heads up, we will patch it

**Comment by miptrel** [comment]
Sorry, I just found out that when I set my system language into English (I was using Traditional Chinese before), the problem seems to be solved.

**Comment by waldispuhl** [comment]
Great. Keep us updated if you have any other issue. We will release a upgraded version of the game soon.
