### ISSUE TITLE
Ranking does not get updated.

### ISSUE THREAD

**Issue by SLall910** [McGill-CSB/PHYLO#112]
I've noticed for the last week or some that my ranking does not change or update when I play phylo. I need this for my class and have been playing constantly but the numbers stay the same. I have tried playing on my phone, desktop, laptop and school computers but it is the same issue.

**Comment by waldispuhl** [comment]
The most likely reason could be that you completed a puzzle you previously played. The ranking uses only your best result. We can provide you a list of all puzzle you played including duplicates if you need it (your instructor can request it to us as well).
If you wish to avoid playing the same puzzles several times, you can find a list of all available puzzles at: http://phylo.cs.mcgill.ca/teaching/puzzles.php
You can click on the ID to access each puzzle. 
Please, let us know if that explain/solve your issue.

**Comment by SLall910** [comment]
I went through the list you sent me and played the ones that I haven't played before and they counted but most of them are the same disease but have different ID numbers and when I play the same disease nothing happens

**Comment by SLall910** [comment]
I try to do different difficulty levels and different categories to see if I would get any new games but I'm playing about 50 a day and only 5 are being counted

**Comment by waldispuhl** [comment]
OK. Thanks for the feedback. We'll investigate that and get back to you ASAP. All puzzles are stored, so you get credit for all puzzles you played.

**Comment by waldispuhl** [comment]
@SLall910 We checked the ranking and everything is correct. You played indeed 946 puzzles, among which 379 are unique. The latter is the number reported in the ranking. We keep only the best score for each puzzle you played.
Please, email us directly if you need a complete list of all puzzles you played, including duplicate. We will be happy to provide you any data you need to show your participation to Phylo.
