### ISSUE TITLE
Registration doesn't explain what is wrong when validation of email or password fails

### ISSUE THREAD

**Issue by movermeyer** [McGill-CSB/PHYLO#116]
Steps to reproduce:

1. Click Register
2. Enter a valid username and email
3. Enter a password (ex. ["SomeSimplePasswordUntilTheyFixPaste"](https://www.facebook.com/phyloDNApuzzles/posts/2014573371904134?comment_id=2014579561903515&comment_tracking=%7B%22tn%22%3A%22R%22%7D))
4. In the password confirmation box, type a similar (but typoed) password (ex. "SomeSimplePasswordUntilTheyFixPast**r**")

The error message says "Please fix error in field below". 

It does not explain which fields need changing, nor why they need changing.
Ideally, the password confirmation field would be highlighted in red, and the error message would say something like "Password and Confirm Password fields do not match"

Visually:

![register](https://user-images.githubusercontent.com/1459385/38940004-b87433f0-4318-11e8-8802-4a91b6babaac.gif)

Similarly, if you enter an invalid email address (ex. "a"), the email field should be highlighted, and the error message should be something similar to "Invalid email address".

You already give a nice error message when the username already exists, so the code for custom messages is already in place. Hopefully, it's a simple matter to extend it to these cases too.

Tested on: Phylo (Web) v1.1.7.7? Or it 2.0.1? `2.0.1` is what the McGill loading page says, but the top of the site says `1.1.7.7`

**Comment by waldispuhl** [comment]
Thanks. We need to fix this indeed.

The version# on the webpage will be removed soon. the right version# is the one of the app.

**Comment by chrisdrogaris** [comment]
Hi movermeyer

We have fixed the issue on the latest version on this link:
https://phylo.cs.mcgill.ca/play.html

I have also attached a screenshot 

![registration-bug-fixed](https://user-images.githubusercontent.com/4981346/39840326-10c4fc8e-53ad-11e8-8485-20f5cfe14fc8.png)

Thanks for the feedback.
