### ISSUE TITLE
sometimes mustache code is not translated (on tablets only ?)

### ISSUE THREAD

**Issue by waldispuhl** [McGill-CSB/PHYLO#12]

**Comment by alfredkam** [comment]
hmm it translates on ipad, may be u need to wait a bit before a translation is in.

**Comment by waldispuhl** [comment]
I experienced the problem on ipad too. It's very seldom though. I expect sync issues. Lets just keep an eye on it for now.

**Comment by waldispuhl** [comment]
Mustache tags are not substituted at the end screen for puzzles with 9 & 10 sequences (several tries). Can you check if you can reproduce it?

**Comment by waldispuhl** [comment]
@alfredkam : Did you experienced that bug on ipad mini & nexus 7? Is a fix needed or should we leave it as it is for now? (in the latter case, close the issue)
