### ISSUE TITLE
OpenPhylo user registration clears all fields when password conformance checks fail

### ISSUE THREAD

**Issue by movermeyer** [McGill-CSB/PHYLO#121]
When you register for a new user in the [OpenPhylo UI](http://kovik.cs.mcgill.ca/#/registerUser), there is no indication what is required for the password (ex. >=8 characters). It only checks the conformance server side:
![reg1](https://user-images.githubusercontent.com/1459385/39364946-40f7d788-4a1f-11e8-8b3d-206abfc63fdd.png)

Annoyingly, when you password doesn't conform to the password rules, it clears all of the fields in the form (not just the password ones), and gives you the message in an alert box.

![reg2](https://user-images.githubusercontent.com/1459385/39364953-46fb74c8-4a1f-11e8-9338-067c8432ebe9.png)

Ideally, conformance to the password policies would be checked on the client side, and the error message would be displayed in-line with the password field.

The part that most annoyed me is having to enter everything again, instead of just correcting the password field. Admittedly this is a minor annoyance. But it causes unnecessary negative emotions just as a user is beginning to use Phylo.

[Animated Gif version](https://imgur.com/a/hf9IifP)

**Comment by akashzcoder** [comment]
Confirmation is already on the client side, but yes form details don't have to be reset.  We will resolve that today. This is the first of the many sprint releases that we will be doing for OpenPhylo before the final release.

**Comment by movermeyer** [comment]
Thanks. I've updated the title.

**Comment by akashzcoder** [comment]
I have updated this along with better and more specific validation messages. Thank you very much! :)
