### ISSUE TITLE
facebook login

### ISSUE THREAD

**Issue by alfredkam** [McGill-CSB/PHYLO#23]
first attempt never works and i retrieve a string of json, think its requesting too much personal info...

**Comment by waldispuhl** [comment]
firsts attempt works from me. It's a 2 step (server side) registration process to avoid CSRF attacks.
None of the information there are used beside name & email. Though I cannot request less as it is what is returned by the provider.

**Comment by alfredkam** [comment]
i always see the entire json string on first attempt and page does not reload either.

**Comment by waldispuhl** [comment]
Social login worked fine for me until now. Do you still have this bug or can we close this issue for now?

**Comment by waldispuhl** [comment]
I close it for now. Works fine for me. re-open if you experience it again.
