### ISSUE TITLE
img specie is missing on lvl #137

### ISSUE THREAD

**Issue by waldispuhl** [McGill-CSB/PHYLO#26]

**Comment by alfredkam** [comment]
its missing - myoluc1.png

??? is that even an animal name...?

**Comment by waldispuhl** [comment]
Its a bat :) "myotis lucifugus" Can we use bat.png ?

**Comment by alfredkam** [comment]
its one of the uncategorized node names from the parsing the json

**Comment by waldispuhl** [comment]
which file?

**Comment by alfredkam** [comment]
tree.core.js 

just added it to the parser.

**Comment by waldispuhl** [comment]
ok
