### ISSUE TITLE
Tiles are vertically shifted

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#39]
See attached image, as you go down in the grid, the tiles are shifted by a small amount upward.

Note: using http://phylo.cs.mcgill.ca/beta/#!/EN/play

Regards.

![Phylo 2012-12-13_165813](https://f.cloud.github.com/assets/3037251/12004/a91c0d3e-4570-11e2-8d05-06024bcbeb5b.jpg)

added nexus 7 to this list

**Comment by alfredkam** [comment]
which browser are you using?

**Comment by HolterPhylo** [comment]
Browser is

![Browser 2012-12-13_213027](https://f.cloud.github.com/assets/3037251/12489/b5440640-4596-11e2-858b-8cfd6472a5e0.jpg)

OS is Win 7 64bit Professional with all updates

**Comment by alfredkam** [comment]
@waldispuhl did we change the css by chance?  Used to be fine

**Comment by alfredkam** [comment]
@waldispuhl this issue only exists with FF on Windows

**Comment by waldispuhl** [comment]
I did not touch the css of the game. I guess it's a W7 issue.

**Comment by HolterPhylo** [comment]
I checked on Chrome and it is ok, so it is a FF problem not W7.

**Comment by alfredkam** [comment]
current list for this bug
- nexus 7 
- FF

**Comment by ishyca** [comment]
I fix this issue for nexus 7. there is a lock to "landscape view" you have to set in androidmanifest.xml
