### ISSUE TITLE
Smaller blocks in Tutorial, not in game?

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#40]
As shown in these images, the tutorial pages explain that smaller blocks are used to highlight mismatches but they do not appear in game.

![Phylo Tutorial p 1 2012-12-13_170655](https://f.cloud.github.com/assets/3037251/12028/c8cd99da-4571-11e2-8647-6c6219ba016a.jpg)
![Phylo Tutorial p 2 2012-12-13_170655](https://f.cloud.github.com/assets/3037251/12031/ed7a7a6e-4571-11e2-8459-c0fda7e4ffac.jpg)

and following pages in the tutorial.

Regards

**Comment by waldispuhl** [comment]
If you do not see them in the game it might be a browser compatibility problem. Which OS/Browser are you using?

**Comment by HolterPhylo** [comment]
Browser is

![Browser 2012-12-13_213027](https://f.cloud.github.com/assets/3037251/12485/4a5895b2-4596-11e2-9732-9356bd66caee.jpg)

OS is Win 7 64bit Professional with all updates

**Comment by HolterPhylo** [comment]
Also ok with Chrome, so a FF problem again.

Anybody can confirm?

**Comment by alfredkam** [comment]
yea only on FF.

**Comment by hoffmado** [comment]
I can confirm that too: got the same problem with Firefox 17.0.1, Win7 64-Bit.
