### ISSUE TITLE
Missing word in tutorial page

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#42]
The word "find" is missing from the end of the first line / beginning of the second line on this tutorial page:

![Phylo Tutorial p 8 2012-12-13_170655](https://f.cloud.github.com/assets/3037251/12068/e241aca6-4573-11e2-833f-df42fc8919fb.jpg)

Regards

**Comment by waldispuhl** [comment]
Thanks for all the notes. I'll fix the tutorial and actually append another section with an example very soon.

**Comment by HolterPhylo** [comment]
Thanks :)

**Comment by waldispuhl** [comment]
fixed. As promised, we added an example in the tutorial as well! (hopefully w/o too many typos ;-) )

**Comment by HolterPhylo** [comment]
Great!
