### ISSUE TITLE
Suggestion: Ranking

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#51]
May I suggest that ranking be based not only on **Total** score but **_also**_ on **number of 3-2-1 stars**.

Its seems to be ordered by Total score and user name at the moment.

![Phylo All-time Ranking 2012-12-18_115719](https://f.cloud.github.com/assets/3037251/19866/aa1bef48-4934-11e2-9855-71425c953d3e.jpg)

**Comment by waldispuhl** [comment]
@HolterPhylo Sorry for the very late answer. I missed this post... You can customize your ranking. Click on the column of your choice to select which parameter to use for ranking.
