### ISSUE TITLE
Weekly score not updated...

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#52]
It seems that the Weekly score is not updated after I have submitted a new puzzle:

![Phylo Weekly Score 2012-12-18_121408](https://f.cloud.github.com/assets/3037251/19903/1b47c384-4937-11e2-8899-dffaab3fdc79.jpg)

My current score:

![Phylo All-time Ranking 2012-12-18_115719](https://f.cloud.github.com/assets/3037251/19912/5d019534-4937-11e2-8533-1dd05068832d.jpg)

**Comment by waldispuhl** [comment]
I'll have a closer closer look at the db but it at this point the rankings do not seem incoherent. Here you show the weekly & All-time ranking. As long as you the number in All-time is larger or equal to the weekly it looks ok. Also, if you replay a puzzle you already played the latter is just counted once. Do you mean that you played a new puzzle that has not been credited?

**Comment by HolterPhylo** [comment]
Yes, I played a new puzzle.  On the all-time tab the total score got updated (and the correct 1-2-3 star count).  The weekly tab scores were not updated.

**Comment by waldispuhl** [comment]
ok I will look at that. Do you remember by any chance your score for this puzzle? (i.e. 1, 2 or 3 stars)

**Comment by HolterPhylo** [comment]
No, sorry.
