### ISSUE TITLE
ID# 58 - Gap question

### ISSUE THREAD

**Issue by HolterPhylo** [McGill-CSB/PHYLO#53]
This is puzzle ID# 58 and the chain for the 1st black box of the tree:
- Why the 1st gap and 2 extends do not show?
- Why the 2nd gap is not an empty column instead?

![Phylo ID58 2012-12-18_144114](https://f.cloud.github.com/assets/3037251/20267/5b1d2be8-494b-11e2-998d-0ff0351e917a.jpg)

**Comment by waldispuhl** [comment]
Supplementary information can be found at : http://phylo.cs.mcgill.ca/eng/faq.html
We use a modified version of the Fitch algorithm to compute ancestors (http://ab.inf.uni-tuebingen.de/teaching/ws06/albi1/script/phylogeny_31Jan2007.pdf). Gaps in sequences are treated as an special nucleotide but as the lowest priority. The sequences are supposed to be the ones giving you the best score at the end. This may not always results in the best ancestor but it works well in practice for the purpose of this game. Note that the expert version allow you to improve the ancestor calculation.
Well, I guess this short paragraph does not give all details you need to understand exactly how the ancestors are calculated. I'll try to write something on that and will post it next week.

**Comment by HolterPhylo** [comment]
Thanks a lot!
