### ISSUE TITLE
Can't retrieve password

### ISSUE THREAD

**Issue by EllenCB** [McGill-CSB/PHYLO#54]
I tried to log in with the email for a different account, which I have use before to play Phylo.  My Uname, Pword combination was rejected, and I tried to rest the Pword.  I got this message after typing my email address into the prompt box:
There was an error when trying to email you at ''.

Win XP, SP3; Firefox 17.0.1

**Comment by waldispuhl** [comment]
Sure. We can fix that easily. There's two potential source of error:
- we dont have your email address
- if you previously registered with the javascript version (2011 alpha release) we may have to add you manually to the database.

Could you please email me directly at jerome.waldispuhl@mcgill.ca and send me your username?

**Comment by EllenCB** [comment]
Thanks. I did previously register with the old version. I'd like to use 
the email ecb01701@gmail.com, and the user name EllenCB if its 
available. If EllenCB is taken, ecb01701 is fine.

Thanks for the update. Its much nicer to play.
Ellen

**Comment by waldispuhl** [comment]
I saw that someone registered today with username 'EllenCB'. I assume its you?
If not I can create a new entry. If you wish to retrieve old data I'll try to dig the previous database.
I'm glad to hear that you like the new design!

**Comment by EllenCB** [comment]
It must have been me. No need to try to dig up the database, but thanks.
Ellen

**Comment by waldispuhl** [comment]
Sounds good. Not a problem. Email me at your convenience, if you wish to retrieve previous data and sync your accounts.
