### ISSUE TITLE
Using the expert mode with a Google connection, and account fusion ?

### ISSUE THREAD

**Issue by amorvan22** [McGill-CSB/PHYLO#58]
Hi, 
I have some questions about the differents connection (pseudo and password, facebook, google, etc...).  First, I really like to use the expert mode, but for now, I use a Google connection, So it's impossible to me to have the expert mode with this count ?  But months ago, i played with an phylo account and I played enought to have this feature, So I'll sum up this in one question :  Could my phylo count stats be fusionned with my Google stats and the expert mode allowed to me ?  If it's possible I would like talking of this with a developper by private message ?

Thanks a lot and sorry for my english mistakes, mine isn't perfect ..

**Comment by waldispuhl** [comment]
Hello, Sure. This can be easily done. Please, email me your username at jerome.waldispuhl@mcgill.ca
Your english is great. Feel to email me in french if you prefer though.

**Comment by waldispuhl** [comment]
I think this issue has been solved. Feel free to re-open the thread if you're not satisfied or need more help here.
