### ISSUE TITLE
contribute-page branch translate.html file

### ISSUE THREAD

**Issue by alfredkam** [McGill-CSB/PHYLO#59]
@andfree ive threw in your translate file in to the contribute-page branch, once you've linked up all the required js files and threw in the bootstrap theme, then ill push it to server

CC'ed @waldispuhl

**Comment by ghost** [comment]
@alfredkam I've merged the translate pages, feel free to push to the server.

**Comment by alfredkam** [comment]
## Done + added missing files

All the best,
Alfred Kam

Sales & Operations | adConnect | akam@adcnx.commailto:akam@adcnx.com
(Canada) +1 514 691 2889 | (China) +852 8125 6586 | (Skype) kamalfred | (QQ) 766522308
(twitter) @alfredkam | (linkedIn) kamalfred | (Weibo) alfredkam
www.adcnx.com
