### ISSUE TITLE
ranking not updated (ipad)

### ISSUE THREAD

**Issue by hoffmado** [McGill-CSB/PHYLO#61]
even if i refresh on the ranking site, the stars/total got stuck at 10(3star) 2(2star) 0(star) 12(total).
in addition the history site only updates if i refresh the browser-tab manually.

i am using an ipad with safari to play - login via facebook.

thank you :-)

update: this is not related to my account, on a PC with mozilla it works fine!

**Comment by waldispuhl** [comment]
Thanks for the feedback. I'll look at that as soon as I can. It seems related to issue #42 . I checked the code recently but couldnt find any bug. at least in the scripts I checked. I'll investigate that more deeply. Just to be sure:
- You played new puzzles right? (i.e. not one you previously played) 
- Did you used a different selection method (e.g. disease select vs difficulty select)?
- I'll check your submission. I assume that I can find you using the same username of your git-hub account or you full name?

Sorry for the inconvenience. I'll credit you the missing puzzle and update your ranking as soon as I'll identify the problem.

**Comment by hoffmado** [comment]
I played new puzzles, that's right. Looking at "History" i have a total of 34 different "level" played actually without a change at the rankings (checking it with IPad!).
And yes, that's the same name: Dominique Hoffmann. (there is a mountain in the background of my picture)

I want to point out again that this is only true if i use IPad+Safari.
If i log in using a PC both works and is updated!

**Comment by waldispuhl** [comment]
Thanks for emphasizing that the problem is on tablets. I was going to look at the server-side scripts but this remark rule them out.
@alfredkam : Can you look at that? You should be the most qualified to investigate this issue.
Btw, indeed the ranking update currently require a refresh but we'll try to see if we can implement a better mechanism in a near future.

**Comment by hoffmado** [comment]
I have to add something to my answer (had to re-check before i post it):

Regarding your 2nd point: If i use "disease select" on IPad i get new levels every time i chose
BUT if i try "difficulty select" i get the same level every time i try it.
For example: selecting 5-6 always gives me level 452.
I didn't think about that until you wrote that point ;-)
