### ISSUE TITLE
Diseases Icons

### ISSUE THREAD

**Issue by benj83** [McGill-CSB/PHYLO#62]
![Phylo](https://f.cloud.github.com/assets/3202135/46532/4ce3a4fa-586c-11e2-960e-658908b2a44a.jpg)

In the attached screenshot, what diseases do the icons stand for?
It would be good if you add their names to the screen... or at least tell us here :)
Thank you very much!
Ben

**Comment by waldispuhl** [comment]
You're very right. We intended to display the legend a the bottom as in the main menu but did not had time to implement it yet. The legend is the following (from left to right and top to down):
1. digestive system diseases 2. heart and circulatory system 3. Cancer
2. metabolic diseases 5. Blood and immune system 6. Sensory system disease
3. Brain and nervous system 8. muscles diseases 9. respiratory system

Sorry for the confusion. It was not clear indeed and we'll try to improve that ASAP.

Thanks for the note!

**Comment by benj83** [comment]
Thank you very much for your response! And I admire you for this wonderful game! :)

**Comment by waldispuhl** [comment]
Thanks a lot. I hope you have fun playing it :)
