### ISSUE TITLE
Wrong classification maybe?

### ISSUE THREAD

**Issue by Aldronaigh** [McGill-CSB/PHYLO#64]
Hi,

ID 110 "Diamond Blackfan Anemia 7" is classified as a brain disease
whereas
ID 61, 62 and 63 "Diamond Blackfan Anemia 7" are classified as a blood disease

**Comment by waldispuhl** [comment]
Thanks for finding that! This is indeed a mistake. I'll fix that ASAP.

**Comment by waldispuhl** [comment]
Thanks again! It should be fixed now.
