### ISSUE TITLE
Game won't load

### ISSUE THREAD

**Issue by cellRus** [McGill-CSB/PHYLO#66]
Look, I'm new to gaming, but there's nothing on the page called PLAY that you can click on that starts the game.  What am I missing?  All I get are the word Random, level, or something about picking a disease, which you can't do because nothing loads.

**Comment by alfredkam** [comment]
Did you try clicking on Random / Level / Disease - it should lead you to another screen to pick either a puzzle size or a specific disease? May i also ask which browser are you using? 
- Thanks Alfred

**Comment by cellRus** [comment]
Hi Alfred,

Yes, I clicked on all three, but no additional screen came up.  I’m using IE-9 I believe.

Thanks for getting back to me.

Nathan

**Comment by DOM93** [comment]
I am having the exact same issue and I have tried waiting to see if this glitch gets fixed, using different internet connections and nothing! I have tried looking everywhere for somewhere that offers support or answers but all I could find was this thing I had to sign up for which just added to the irritation I am feeling trying to get this game to work.

**Comment by waldispuhl** [comment]
which browser are you using? Chrome/Firefox/Safari should be all fine. We experienced some issues with IE in the past.
