### ISSUE TITLE
Google sign in

### ISSUE THREAD

**Issue by wanderingstranger** [McGill-CSB/PHYLO#68]
The sign in with Google option is throwing back "Error: please try again!Original error message: User profile request failed! Google returned an invalide response." I used to have no issue using Google to sign in (which is how I created my account in the first place) but now the option only rarely works. I have since created a new account so that I can continue to track my levels.

**Comment by ishyca** [comment]
Please clear your cookies and retry login using google.

Jerome, I think this may be a problem with how old cookie of hybridauth
somehow conflicting ....

**Comment by waldispuhl** [comment]
Thanks @ishyca . Indeed, clearing your cookie should help. If it's not the case, let me know.
We use a server side login (http://en.wikipedia.org/wiki/OAuth) that could create problem if key values conflict.
