### ISSUE TITLE
Request reformatting of "More Info" given at end

### ISSUE THREAD

**Issue by Durdge** [McGill-CSB/PHYLO#70]
In Chrome, after completing a game with Phylo 2.0 (non-advanced), click the more info button.  The information displayed is verbose, has several spacing typos, and the formatting makes it cumbersome to extract the relevant data.  I tossed in a sentence at the end to indicate number of completions before unlocking "Advanced Mode" (should probably be posted as a separate feature request).  Not sure if formatting is showing up properly, but labels should be left aligned and values left aligned in another column.

Existing Text:
You played level 73.  Remember this ID if you wish to play this level again later!  The DNA in this puzzle has been linked to: Hypertension.  This level has been completed 396 times. 
Users have failed to reach this level 6 times.The high score of this level is: 62 The average score for this level is: 62 Name_Here has the highest score for this level. 

Recommended Text:
## Stats and information about this level

Level ID:           73
Your Score:     62
Average Score:      62
Highest Score:      62
Record Holder:      Name_Here
DNA Association:    Hypertension
Total Completions:  396

You can use the Level ID to play this level again anytime.  
Complete X more puzzles to unlock Advanced mode with harder puzzles and additional features.
Thank you for contributing to Genomic mapping!

**Comment by waldispuhl** [comment]
Thanks. That's useful and we will see if we can implement that soon. An issue though is that we do not have the translation for the 10 languages implemented in Phylo. I like the sentence about the expert version. Thanks!

**Comment by renarena** [comment]
Beside not showing the current count in the info it sometimes shows wrong data.
Highscore is 181 - I scored 179 and are named as highscore holder?????
That is occurring regularly from time to time.

**Comment by MeadMeg** [comment]
The rewrite suggested by Durdge actually requires less translation.
I bet it would be faster to get similar rewrites (use fewer words in the English version) and it would speed up translation overall.

**Comment by waldispuhl** [comment]
Yes. I'm also considering removing the toggle as these informations are almost always useful.
Thanks for your suggestions! It really helps us to improve the design.

**Comment by waldispuhl** [comment]
@Durdge Feature has been added to the new release. Thanks for your suggestion.
