### ISSUE TITLE
Start a documentation/wiki for the sake of making this project more stable

### ISSUE THREAD

**Issue by ishyca** [McGill-CSB/PHYLO#75]
I have been looking into wiki/documentation framework for JavaScript since we are using Javascirpt and Phonegap/cordova and both technologies change rather unpredictably. And I found this website. 

 http://dailyjs.com/2011/01/13/framework-part-46/

I suggest that we have one documentation like Docco for inline and github one for all the installation/building FAQ. 

I will test Docco for android branch after fixing css issue....

**Comment by alfredkam** [comment]
sure go ahead
