### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by AuthorND** [McGill-CSB/PHYLO#76]
Is there any way to turn the music off? I'm finding it very repetitive, and I'd rather be able to listen to my own music while playing.

**Comment by waldispuhl** [comment]
Absolutely. You just need to click on the bottom-right button (speaker icon). It should turn off the music.

**Comment by ishyca** [comment]
Hey AuthorND,
    You can shut off the music by clicking the volume button at the bottom
left of the game next to the bucket. Hope you enjoy the game more from now
on.

Kira
On Mar 30, 2013 3:59 PM, "AuthorND" notifications@github.com wrote:

Is there any way to turn the music off? I'm finding it very repetitive, and
I'd rather be able to listen to my own music while playing.

—
Reply to this email directly or view it on
GitHubhttps://github.com/McGill-CSB/PHYLO/issues/76
.
