### ISSUE TITLE
push blocks together

### ISSUE THREAD

**Issue by renarena** [McGill-CSB/PHYLO#80]
I would like an ability (option?) to get all blocks pushed together on each new row (to left, right or even middle).
Thats the first thing i do nearly always  before i begin to think about the block colors.
Its a lot of avoidable mouse action (safe the hands of your players from getting RSI :-)

**Comment by alfredkam** [comment]
if you double click, you will have the option to select multiple blocks and push them together

**Comment by renarena** [comment]
I know this, but its 4 mouse clicks too. Its grindingly to do this. I want the blocks pushed together rather then forced to do it myself. Whats about a left/right arrow to click which pushes the new blocks in this direction?
RSI is a serious problem, even if most people dont know it.
