### ISSUE TITLE
ADVICE WANTED! Undergradute Genetics Instructor would like students to play Phylo

### ISSUE THREAD

**Issue by moonhardt** [McGill-CSB/PHYLO#84]
Greetings,

I am teaching Genetics at a major university this fall and I would like to offer extra credit to the student who play Phylo.  I have several questions about how to best go about this.
1. How will I know which students have played the game?  The only thing I have thought of so far is having the students take a screenshot of the game at a certain point and submit it to me.  If anyone has a better idea, I would really appreciate it.
2.  How much of the game should I make the students play?  I would be happy to hear about the minimum playing time or level a student should achieve for credit.

Thank you!

**Comment by waldispuhl** [comment]
Hi @moonhardt 

We will be delighted to help you to make the best possible use of Phylo for your class. Currently, you can:
1. You can ask the student to register with a username following a predefined syntax (E.g. <class#>_<studentname>. Then you can look for your student with the key word <class#> in the search box of the ranking page : http://phylo.cs.mcgill.ca/#!/EN/ranking
2. Currently, all players who completed 20 puzzles have access to our "expert" interface (http://phylo.cs.mcgill.ca/expert/welcome.php). So 20 puzzles could be a good number. But you may want to ask more or less? Another possibility is to use the 3-stars score (3 stars stands for high-score and 1 star for matching the computer solution). So 3 to 5 high scores could be a good number? (N.B. this score does not account for the difficulty of the puzzle). In my class, I used to ask the student to complete at least 20 puzzles and gave a bonus to the one with the highest number of high scores.

Alternatively, if you want to input some specific alignments we can do that too. We are testing a submit interface I could share with you.  

I would be also happy to discuss with you of anything we could do to improve Phylo's interactivity. We could for instance imagine to develop an interface teacher. Please, let me know if you would be interested to discuss that further.

**Comment by moonhardt** [comment]
Thank you for your help!  :-)  

Let me make sure I understand this syntax thing:  So how about the first four letters of the last name, the first two letters of their first name, and then underscore_ vcu?  So an example would be LASTFI_VCU?  And how will I search for this?  Just go to the board and search for _VCU?

I'm note sure how many this class will seat yet, but possibly about 200 or 300 per section?  Is this still the best method?  Or is there a better method for a large size group?

20 puzzles might be a good number?  How long do you think that will take the average novice player?  I want the students to play, but I don't want them to dislike it because I've made them play too long to get credit.  I think I'm mainly worried about generating 'false results' if some of the players get frustrated, and just start randomly clicking in hopes of getting credit.  Any thoughts on this?  Will the computer program be able to filter out 'bad fits' while still recognizing 'good fits'?

I like the idea for 3 to 5 high scores.  And that way the students can do the easiest puzzles if they are having trouble.  And I REALLY like the idea of giving the top students bonus points.  That I'm definitely going to do.

I don't think picking specific alignments is a good idea for my particular situation, because then one student might find the best answer and then share it with all the others.  Students are savvy like that.

I'd be very happy to continue this conversation publicly so other teachers can see, but we can also move to private email so I can share more specifics of my situation.  Please feel free to email me at hardtta@vcu.edu

**Comment by waldispuhl** [comment]
That's correct. The method you suggested should work fine. You just need to go to the board and search for _VCU indeed. A couple of hundred of student will not be a problem for our system but it might take a lot of time to extract all scores... I'll try to find a better way to do this. It might take 1-2 weeks to have a fully functional interface, but the student can start to play anyway. 
I'll email you privately to set up and test this interface, but I'll come back here once it'll be stable. Make it available to all teachers is important to us!

**Comment by waldispuhl** [comment]
The interface is now accessible at : http://phylo.cs.mcgill.ca/teaching/
I hope it'll help!
