### ISSUE TITLE
Music available for download? 

### ISSUE THREAD

**Issue by durb** [McGill-CSB/PHYLO#85]
I like the music! Is there anyway to download it from Amazon or iTunes? Is this from a specific album? I was unable to learn about the music from the Credits. Thanks for any info.

**Comment by waldispuhl** [comment]
Thanks! It's not on Amazon of iTunes but I will set up a webpage for downloading all songs. Actually, I was thinking of adding more track to Phylo by the end of August. I'll keep you posted here ASAP.

**Comment by durb** [comment]
Thank you!

**Comment by waldispuhl** [comment]
I put online other tunes at : http://www.cs.mcgill.ca/~jeromew/pub/Valent/
Some of them will be included in the next upgrade.
The style may vary, but I hope you'll like at least some of them!

**Comment by durb** [comment]
Beautiful. Thanks!
