### ISSUE TITLE
Add text to the Disease selection page

### ISSUE THREAD

**Issue by MeadMeg** [McGill-CSB/PHYLO#86]
Hi - the icons are cute, but they don't tell me anything. Can you please add TEXT as well. Then I'll learn what the icons mean - and can choose a disease.

**Comment by waldispuhl** [comment]
Yes. That's a good suggestion (and sorry if it was not obvious). Actually, we're currently reformatting that page. We hope to release soon an upgrade that will fix many features mentioned in this forum.

**Comment by MeadMeg** [comment]
Hi,

Wow - I didn't think to get a reply, since most of the posts are 5 months old or older.

Thanks so much for responding!

Mead

**Comment by waldispuhl** [comment]
Features has just been added to the new release. Thanks for your feedback!
