### ISSUE TITLE
Numbers Everywhere

### ISSUE THREAD

**Issue by mrsthursday** [McGill-CSB/PHYLO#87]
Just curious about the small, in size, number on the far right of the progress bar. Is that the number we should aim for or is it the highest score that has been achieved by a player? I don't mean the par. Thanks

**Comment by waldispuhl** [comment]
Are your referring to the gray number ? It is simply the value of the scale at the right extremity. Bars are not spaced linearly though. If you find it confusing, we will try to make it clearer.

**Comment by mrsthursday** [comment]
Thanks. That answers my question.
