### ISSUE TITLE
sound during loading of the game

### ISSUE THREAD

**Issue by marie-s** [McGill-CSB/PHYLO#91]
I like to play without sound and the sound of the loading of the game remain after asking for no sound and music.
Thanks

**Comment by waldispuhl** [comment]
We are planning to allow users to control sounds (effect & music) from the settings panel. For now, we'll remove the loading sound effect when the sound is turned off.

**Comment by marie-s** [comment]
Thanks, I like to listen to music when I play

**Comment by marie-s** [comment]
There is a problem with the new option
The sounds and music come back when I open the first puzzle.

**Comment by waldispuhl** [comment]
Thanks. We're actually currently fixing a series a small bugs (we didnt know about that one though :) ). Everything should be fixed by tonight.

**Comment by waldispuhl** [comment]
We just pushed an update. Did it fix your issue or is does it still needs to be addressed ? (could you eventually give us you OS & Browser ?)

**Comment by marie-s** [comment]
The issue is fixed 
Win 8.0 chrome, firefox and IE10
Thanks
