### ISSUE TITLE
No star on iOS

### ISSUE THREAD

**Issue by Renatey** [McGill-CSB/PHYLO#96]
Hello! I have beaten the par but no star is visible. I'm playing on IPad iOS 7 via Safari browser.

**Comment by waldispuhl** [comment]
Do you mean the star on the bottom right corner of the game board ? Could you please send us the puzzle you played. Thanks.

**Comment by Renatey** [comment]
Yes, I mean that one. Without seeing it I cannot submit any result. I tried puzzles #1, 2, 44, 80 and others. I believe the problem is in using mobile: even on this page http://phylo.cs.mcgill.ca/#!/mobile/EN (or RU) HISTORY link is out and appears only after refreshing page. But I cannot refresh puzzle page. In puzzle with ID 3 par is 14. I make 24 but no star appears.

**Comment by waldispuhl** [comment]
Thanks, we'll investigate that. I'll keep you updated ASAP.

**Comment by waldispuhl** [comment]
We released a upgrade. The bug you mentioned should have been fixed. Let us know if it works fine. Otherwise we'll investigate further.

**Comment by Renatey** [comment]
Still out of order.  No visible stars on http://phylo.cs.mcgill.ca/#!/EN/Play. Maybe it's better to make star visible but inactive till the par is beaten? History link on main page still appears only after page refreshing. Sorry.

**Comment by waldispuhl** [comment]
Did you try to refresh your cache ? I just tried on the configuration and it worked.

**Comment by Renatey** [comment]
Now it works perfectly! Thanks!
